name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.5'

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Build with build.sh
        run: ./build.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto-release-${{ github.sha }}
          files: |
            lotus
            lotus.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}